### PR TITLE
fix: Docker file setup did not allow migrations to run

### PR DESCRIPTION
**Pull request by filipecabaco**
## What kind of change does this PR introduce?
Overall simplification on how we startup Realtime
Also did the following changes:
* Removed minio
* Cleaned up docker image to remove tailscale
* Removed / Renamed FLY specific environment variables
* Removed limit.sh and wrapper.sh in favor of a single run.sh script to simplify deployment
* Migrations are always run when Realtime is started
* Seeding is ran if `SEED_SELF_HOST` is true

this also simplifies docker-compose and cli setup for realtime.

### CODE REVIEW

**Comment by barrownicholas** [comment]
for visibility, this would also close https://github.com/supabase/realtime/issues/1080

**Review by chasers — APPROVED** [review]

**Comment by filipecabaco** [comment]
Screenshot 2024-06-24 at 14 38 20
working on docker compose of supabase repo (self-hosted example)

**Comment by filipecabaco** [comment]
Screenshot 2024-06-24 at 14 54 23
working in cli

**Comment by filipecabaco** [comment]
those will need different PRs because we're now building locally 😅 (supabase/realtime:dev)

**Pull request merged**
