### PR TITLE
fix: override `max_header_value_length` using environment variable

### PR DESCRIPTION
**Pull request by nbarrow-inspire-labs**
## What kind of change does this PR introduce?

Bug fix for https://github.com/supabase/realtime/issues/761:
- introduces a new environment variable `MAX_HEADER_LENGTH` that can be used to override config -> http -> protocol_options -> max_header_value_length from its default value in Elixr (4096)
- If no value is set, the Elixr default of 4096 will continue to be used
- updates README to reflect these changes

## What is the current behavior?

With SSR and the use of cookies to authenticate on the server, all cookies need to be sent to Supabase requests, including Realtime. If these cookies exceed the (rather low) default of 4096 (which, with an auth provider for supabase, can happen extremely easily), realtime subscriptions fail with a 431 error. 

Edit: we are using Keycloak as our Supabase authentication provider, and it looks like Keycloak is a bit notorious for large cookies (see https://github.com/supabase/realtime/issues/761#issuecomment-1863507257). Hence the further need to increase the limit, but in a dynamic fashion (for users who wish to retain the security benefits of smaller limits and don't use Keycloak or other services with larger cookies).

## What is the new behavior?

With the new behavior, a user could specify a `MAX_HEADER_LENGTH` environment variable to a higher value (such as `8192`, doubling the limit) to cease the 431 errors.

## Additional context

See https://github.com/supabase/realtime/issues/761

Edit: I test-built with these changes locally and it 100% fixed the issue.

### CODE REVIEW

**Comment by nbarrow-inspire-labs** [comment]
I did test-build this locally and it 100% fixed the issue with `MAX_HEADER_LENGTH: 8192` in docker compose.

**Comment by nbarrow-inspire-labs** [comment]
@filipecabaco when you have a chance, can you take a look at this? It seems partially related to https://github.com/supabase/realtime/issues/746 which you helped me with a week or so ago. This should fully solve the rest of the problem (https://github.com/supabase/realtime/issues/761).

**Comment by filipecabaco** [comment]
Hey! just a FYI that I will take a look later today 👁️

**Comment by nbarrow-inspire-labs** [comment]
Just wanted to see if anyone's had the chance to take a look at this yet? It should be a pretty quick review (hopefully!)

**Comment by filipecabaco** [comment]
not yet sorry... 😓 tricky week. there's one change needed in the mix.exs file to bump the minor version to (2.25.50) and will check the remainder of the code now

**Comment by filipecabaco** [comment]
yep looks good, just needs that change in the mix.exs to 2.25.50 since I'm going to merge 2.25.49 now

**Comment by nbarrow-inspire-labs** [comment]
@filipecabaco awesome (and no worries on the delay!) thanks for checking. I just bumped the version in `mix.esx` so it should be good to go after your pull.

**Review by filipecabaco — APPROVED** [review]

**Comment by filipecabaco** [comment]
going to rebase and merge to fix the conflict. thank you for the help 🙏

**Comment by nbarrow-inspire-labs** [comment]
Appreciate the help, thanks @filipecabaco !

**Pull request merged**
