### PR TITLE
fix: Longpoll configuration setting properly session

### PR DESCRIPTION
**Pull request by filipecabaco**
## What kind of change does this PR introduce?

Longpoll configuration setting properly session

### CODE REVIEW

**Review by chasers — APPROVED** [review]

**Comment by chasers** [comment]
I was thinking this should be a separate extension where `event` would be `listen_notify` or similar.

And users would have to include this `extension` in their RLS policies. 

I feel like this warrants a separate section in the docs and this would make it a real "extension".

Clients should not be able to send each other `listen_notify` messages so we could filter these out this way also.

**Review by chasers — CHANGES_REQUESTED** [review]
I was thinking this should be a separate extension where `event` would be `listen_notify` or similar.

And users would have to include this `extension` in their RLS policies. 

I feel like this warrants a separate section in the docs and this would make it a real "extension".

Clients should not be able to send each other `listen_notify` messages so we could filter these out this way also.

**Comment by filipecabaco** [comment]
> I was thinking this should be a separate extension where `event` would be `listen_notify` or similar.
> 
> And users would have to include this `extension` in their RLS policies.
> 
> I feel like this warrants a separate section in the docs and this would make it a real "extension".
> 
> Clients should not be able to send each other `listen_notify` messages so we could filter these out this way also.

is this for this PR or the other one? 😅

**Review by chasers — APPROVED** [review]

**Comment by chasers** [comment]
Ya yep, approved.

**Pull request merged**
