### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by milliyin**
## What kind of change does this PR introduce?

Bug fix

## What is the current behavior?

[Please link any relevant issues here.](https://github.com/supabase/realtime/issues/1066)

## What is the new behavior?

removed the comma and updated the version too.

## Additional context

non

### CODE REVIEW

**Comment by milliyin** [comment]
@filipecabaco Can you check now.

**Comment by filipecabaco** [comment]
can you rebase main against your fork? it seems something might not be properly working in the CI side

**Comment by w3b6x9** [comment]
@milliyin thanks for your contribution! can you set the version to `2.29.16` and then we can get this in? cc @filipecabaco

**Comment by milliyin** [comment]
@w3b6x9 i did changed the version,

**Review by w3b6x9 — APPROVED** [review]

**Comment by filipecabaco** [comment]
Thank you @milliyin for the update and sorry for taking so long merging and taking so long to merge it 🙏

**Comment by milliyin** [comment]
Yeah no worries, you can close the issue mentioned in the starting.

**Pull request merged**
